# fly.toml app configuration file generated for deals on 2023-09-25T08:12:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "deals"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
